@host = http://localhost:5017

### Spot create from TMS
POST {{host}}/api/v1/integrations/spots
Content-Type: application/json

#Request(string UserEmail, string Route, decimal Price, Status.Spot? Status, DbModels.ContactPersonDetail? ContactPerson);
{
    "UserEmail": "amikulec@sostmeier.pl",
    "Route": "PL43->DE01",
    "Price": 500,
    "Status": 1,
    "ContactPerson": {
        "Name": "Test",
        "Mobile": "+491252213",
        "Email": "test@op.pl"
    },
    "Deadline" : "2026-10-03T08:14:00+02:00"
}

### Get Spot
@spotId = 01a0f3bd-4e8d-70bb-8fae-afa5937ea793
GET {{host}}/api/v1/integrations/spots/{{spotId}}

### Add Offer
@spotId = 01a0faec-b0e4-77db-957c-c3a143ef8a45
POST {{host}}/api/v1/integrations/offers
Content-Type: application/json

{
    "SpotId": "{{spotId}}",
    "CreateByUserId": "01a0f794-41dc-7fd0-ab64-159c9ec07659",
    "CreateForUserId": "01a0f794-41dc-7fd0-ab64-159c9ec07659",
    "Value": 600
}
